# general defines

CXX=/usr/local/gcc335/bin/g++
# CXX=g++
# CC=g++

LDLIBS=-lilocplex -lconcert -lcplex -lpthread -lm
LDFLAGS=-L/usr/local/ilog/cplex101/lib/ia64_RHEL3.0_3.2/static_pic -L/usr/local/ilog/concert23/lib/ia64_RHEL3.0_3.2/static_pic
CXXFLAGS=-I. -I/usr/local/ilog/cplex101/include -I/usr/local/ilog/concert23/include -DIL_STD -O

# general rules

clean : 
	rm -f opt_draft *-2x2.pdf *.o *.nav *.snm *.bm *.out *.flc *.blg *.aux *.bak *.toc *.lof *.log *.dvi *~ *.ps core backup.tar.gz


